# Generated by Django 5.1.4 on 2025-01-16 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_categoria_etiqueta_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria', to='blog.categoria'),
        ),
        migrations.AddField(
            model_name='post',
            name='etiqueta',
            field=models.ManyToManyField(related_name='etiqueta', to='blog.etiqueta'),
        ),
    ]
