# Generated by Django 5.1.4 on 2025-01-16 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.categoria'),
        ),
        migrations.AlterField(
            model_name='post',
            name='etiqueta',
            field=models.ManyToManyField(related_name='posts_etiqueta', to='blog.etiqueta'),
        ),
    ]
